name: Build website

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [8.1]
        setup: [prefer-stable]

    name: Build website

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-v3-php-${{ matrix.php }}-${{ matrix.setup }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-v3-php-${{ matrix.php }}-${{ matrix.setup }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Build website
        run: |
          cp -r src/site/rst/schema src/site/resources/web/
          composer build-website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CNAME: pdepend.org

      - name: Archive generated website
        uses: actions/upload-artifact@v3
        with:
          name: Website
          path: dist/website

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/website/
